set_day_mode:
  name: "Set Day Mode"
  description: "Sets the Winkhaus door to day mode."
  target:
    entity:
      - integration: "winkhaus_doorclient"
        domain: "lock"

set_night_mode:
  name: "Set Night Mode"
  description: "Sets the Winkhaus door to night mode."
  target:
    entity:
      - integration: "winkhaus_doorclient"
        domain: "lock" 

get_system_state:
  name: "Get System State"
  description: "Fetches the detailed system state from the device and prints it to the Home Assistant log."
  target:
    entity:
      - integration: "winkhaus_doorclient"
        domain: "lock" 